[details]
title = "My app"
description = "Site description as it will appear on OpenGraph"
author = "me"
url = "https://www.floatingintheclouds.com"

[paths]
data = "data"
temp = "temp"

[basicauth]
active = false
user = "user"
secret = "password"